# src/app/core/config/environments/base.yaml
app:
  name: "E-commerce Gateway"
  version: "1.0.0"
  api_prefix: "/api/v1"

cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE"]
  allow_headers: ["*"]

services: {}
