app:
  name: "E-commerce Gateway"
  version: "1.0.0"
  api_prefix: "/api/v1"

cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"]
  allow_headers: ["*"]
  allow_headers:
    - "Authorization"
    - "Content-Type"

server:
  host: "0.0.0.0"
  port: 8000

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"

services: {}
