# src/app/core/config/environments/development.yaml
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(levelname)s - %(message)s"

services:
  products:
    url: "http://localhost:8001"
    timeout: 30
    enabled: true
  category:
    url: "http://localhost:5000"
    timeout: 30
    enabled: true
  orders:
    url: "http://localhost:8002"
    timeout: 30
    enabled: true
